export default {
    GET_DASHBOARD_EMBED_URL: 'GET_DASHBOARD_EMBED_URL',
    GET_DASHBOARD_EMBED_URL_SUCCESS: 'GET_DASHBOARD_EMBED_URL_SUCCESS',
    GET_DASHBOARD_EMBED_URL_FAILURE: 'GET_DASHBOARD_EMBED_URL_FAILURE',
};