export default {
    GET_LOCATIONS_BY_TYPE: 'GET_LOCATIONS_BY_TYPE',
    GET_LOCATIONS_BY_TYPE_SUCCESS: 'GET_LOCATIONS_BY_TYPE_SUCCESS',
    GET_LOCATIONS_BY_TYPE_FAILURE: 'GET_LOCATIONS_BY_TYPE_FAILURE',
};