export default {
  GET_PATIENTS_LOCATION: 'GET_PATIENTS_LOCATION',
  GET_PATIENTS_LOCATION_SUCCESS: 'GET_PATIENTS_LOCATION_SUCCESS',
  GET_PATIENTS_LOCATION_FAILURE: 'GET_PATIENTS_LOCATION_FAILURE',
};
