export default {
    GET_PERSONS_BY_WARD: 'GET_PERSONS_BY_WARD',
    GET_PERSONS_BY_WARD_SUCCESS: 'GET_PERSONS_BY_WARD_SUCCESS',
    GET_PERSONS_BY_WARD_FAILURE: 'GET_PERSONS_BY_WARD_FAILURE',
    CLEAR_GET_PERSONS_BY_WARD: 'CLEAR_GET_PERSONS_BY_WARD'
};