export default {
  SEARCH_HOSPITAL_DETAILS: 'SEARCH_HOSPITAL_DETAILS',
  SEARCH_HOSPITAL_DETAILS_SUCCESS: 'SEARCH_HOSPITAL_DETAILS_SUCCESS',
  SEARCH_HOSPITAL_DETAILS_FAILURE: 'SEARCH_HOSPITAL_DETAILS_FAILURE',
};
