import { takeLatest } from 'redux-saga/effects';
import loginActions from '../actions/LoginAction';
import routesActions from '../actions/RouteToPathAction';
import resetPasswordActions from '../actions/ResetPasswordAction';
import getZonesAction from '../actions/GetZonesAction';
import getPersonsByWardAction from '../actions/GetPersonsByWardAction';
import getPersonsDetailAction from '../actions/getPersonsDetailAction';
import addContractedPersonsAction from '../actions/addContractedPersonsAction';
import getLocationsByTypeAction from '../actions/GetLocationsByType';
import searchHospitalListAction from '../actions/searchHospitalListAction';
import updateContractedPersonsAction from '../actions/updateContractedPersonsAction';
import getPatientsLocationAction from '../actions/getPatientsLocation';
import loginSaga from './LoginSaga';
import routesSaga from './RouteUrlsSaga';
import resetPasswordSaga from './ResetPasswordSaga';
import getAllZones from './GetAllZonesSaga';
import getPersonsByWard from './GetPersonsByWardSaga';
import getPersonsDetailSaga from './getPersonsDetailSaga';
import getLocationsByType from './GetLocationsByTypeSaga';
import addContractedPersonsSaga from './addContractedPersonSaga';
import updateContractedPersonsSaga from './updateContractedPersonsSaga';
import getDashboardEmbedAction from '../actions/GetDashboardEmbedAction';
import getDashboardEmbedUrl from './GetDashboardEmbedSaga';
import searchHospitalNameSaga from './searchHospitalNameSaga';
import getPatientsLocationSaga from './getPatientsLocationSaga';

export default function* saga() {
  yield takeLatest(loginActions.INITIATE_LOGIN, loginSaga);
  yield takeLatest(routesActions.ROUTE_TO_PATH, routesSaga);
  yield takeLatest(resetPasswordActions.RESET_PASSWORD, resetPasswordSaga);
  yield takeLatest(getZonesAction.GET_ALL_ZONE, getAllZones);
  yield takeLatest(getPersonsByWardAction.GET_PERSONS_BY_WARD, getPersonsByWard);
  yield takeLatest(getPersonsDetailAction.GET_PERSONS_DETAILS, getPersonsDetailSaga);
  yield takeLatest(addContractedPersonsAction.ADD_CONTRACTED_PERSONS, addContractedPersonsSaga);
  yield takeLatest(getLocationsByTypeAction.GET_LOCATIONS_BY_TYPE, getLocationsByType);
  yield takeLatest(searchHospitalListAction.SEARCH_HOSPITAL_DETAILS, searchHospitalNameSaga);
  yield takeLatest(updateContractedPersonsAction.UPDATE_CONTRACTED_PERSONS, updateContractedPersonsSaga);
  yield takeLatest(getDashboardEmbedAction.GET_DASHBOARD_EMBED_URL, getDashboardEmbedUrl);
  yield takeLatest(getPatientsLocationAction.GET_PATIENTS_LOCATION, getPatientsLocationSaga);
}
